version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    networks:
      - devnet
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ../backend:/app
    working_dir: /app
    command: mvn spring-boot:run
    networks:
      - devnet
  postgres:
    image: postgres:latest
    container_name: plugpoint-db
    ports:
      - "5555:5432"
    environment:
      POSTGRES_DB: plugpoint
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - devnet

volumes:
  pgdata:
networks:
  devnet:
    driver: bridge
